import Head from "next/head";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import { appLogo, serverRequest } from "@/constants/variables/global.vars";
import { useGlobalProvider } from "@/constants/providers/global.provider";
import MobileHome from "./mobile";
import DesktopHome from "./desktop";
import { GetServerSideProps } from "next";
import { APIArrayResponse } from "@/constants/types/global.types";
import { FC } from "react";

{/*const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});*/}
export interface HomePageContentProps {
  trending: APIArrayResponse | undefined;
  music: APIArrayResponse | undefined;
  hotsong: APIArrayResponse | undefined;
  mixtape: APIArrayResponse | undefined;
  video: APIArrayResponse | undefined;
  news: APIArrayResponse | undefined;
  recommended: APIArrayResponse | undefined;
}

const Home: FC<HomePageContentProps> = (data) => {

  const { isMobile } = useGlobalProvider();


  return (
    <>
      <Head>
        <title>Naijailoaded</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href={appLogo} />
      </Head>
      {isMobile ? <MobileHome data={data} /> : <DesktopHome data={data} />}
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async () => {
  try {
    // Fire all requests simultaneously
    const [
      trendingRes,
      musicRes,
      mixtapeRes,
      videoRes,
      newsRes,
      recommendedRes
    ] = await Promise.all([
      serverRequest("get", "/posts", { is_trending: true, limit: 5 }),
      serverRequest("get", "/posts", { content_type: "music", limit: 12 }),
      serverRequest("get", "/posts", { category_id: "mix-tape", limit: 12 }),
      serverRequest("get", "/posts", { content_type: "video", limit: 2 }),
      serverRequest("get", "/posts", { content_type: "news", limit: 12 }),
      serverRequest("get", "/posts", {})
    ]);

    return {
      props: {
        trending: trendingRes.data || undefined,
        music: musicRes.data || undefined,
        mixtape: mixtapeRes.data || undefined,
        video: videoRes.data || undefined,
        news: newsRes.data || undefined,
        recommended: recommendedRes.data || undefined,
      }
    };
  } catch (err) {
    console.error("Error fetching home page data:", err);
    return {
      props: {
        trending: undefined,
        music: undefined,
        video: undefined,
        news: undefined,
        recommended: undefined,
      },
      notFound: true
    };
  }
}

export default Home;